# Interaction between iris and python

Show case of opening a persistent class with embedded python.

Every “%” in ObjectScript are automatically replace by “_”

In [17]:
import pandas as pd
pd.options.display.max_rows = 9

df = pd.read_csv('/opt/irisapp/misc/titanic.csv')

#print(df.to_string()) 
#df
#print(df.head(10))
print(df.info()) 
df
df.duplicated()
df.corr()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   name      891 non-null    object
 3   sex       891 non-null    object
 4   age       714 non-null    float64
 5   sibSp     891 non-null    int64
 6   parCh     891 non-null    int64
 7   ticket    891 non-null    object
 8   fare      891 non-null    float64
 9   cabin     204 non-null    object
 10  embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB
None

          survived    pclass       age     sibSp     parCh      fare
survived  1.000000 -0.338481 -0.077221 -0.035322  0.081629  0.257307
pclass   -0.338481  1.000000 -0.369226  0.083081  0.018443 -0.549500
age      -0.077221 -0.369226  1.000000 -0.308247 -0.189119  0.096067
sibSp    -0.035322  0.083081 -0.308247  1.000000  0.414838  0.159651
parCh     0.081629  0.018443 -0.189119  0.414838  1.000000  0.216225
fare      0.257307 -0.549500  0.096067  0.159651  0.216225  1.000000