In [2]:
import pandas as pd
pd.options.display.max_rows = 9

import iris
statement = iris.sql.exec('SELECT * FROM %SYS.ProcessQuery')
df = statement.dataframe()
df
#df = pd.read_csv('/opt/irisapp/misc/titanic.csv')

#print(df.to_string()) 
#df
#print(df.head(10))
#print(df.info()) 
#df
#df.duplicated()
#df.corr()

,id,namespace,routine,linesexecuted,globalreferences,state,pidexternal,username,clientipaddress,clientnodename,...,globalblocks,journalentries,memorypeak,roles,loginroles,datablockwrites,privateglobalreferences,privateglobalupdates,cputime,appframeinfo
0,394,,CONTROL,0,0,RUN,394,,,,...,0,0,58,%All,%All,0,0,0,1660,
1,435,,WRTDMN,651,1839,RUNW,435,,,,...,0,0,58,%All,%All,0,0,0,2780,
2,436,,GARCOL,0,0,RUNW,436,,,,...,0,0,58,%All,%All,0,0,0,0,
3,437,,JRNDMN,3387,326,RUNW,437,,,,...,0,0,58,%All,%All,0,0,0,240,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28,2029,USER,%SYS.Python.SQLResultSet.1,775617,31004,RUN,2029,irisowner,,,...,10,1,1146,%All,%All,37,322,204,4500,
29,1887,%SYS,%SYS.WorkQueueMgr,162795,16393,EVTW,1887,,,-2,...,11,0,256,%All,%All,8,379,181,1550,
30,1888,%SYS,%SYS.WorkQueueMgr,169708,17675,EVTW,1888,,,-2,...,7,213,256,%All,%All,14,186,89,4960,
31,3288,USER,Unknown47,139922,9958,RUN,3288,irisowner,,,...,0,1,860,%All,%All,3,0,0,3130,